---
title: "R Notebook"
output: html_notebook
---

# Overview

Analyse and visualise the Sydney Trains Network.

# Setup

```{r}
rm(list=ls())

library(tidyverse)
library(forcats)
library(stringr)

src_folder <- "data/2017-03-09/"
theme_set(theme_minimal())
```

# Import

```{r}
read_routes <- function () { read_csv(file.path(src_folder, "routes.csv")) }
read_stops <- function () { read_csv(file.path(src_folder, "stops.csv")) }
read_shapes <- function () { read_csv(file.path(src_folder, "shapes.csv")) }
read_trips <- function () { read_csv(file.path(src_folder, "trips.csv")) }
read_stop_times <- function () { read_csv(file.path(src_folder, "stop_times.csv")) }
```

# Transform

```{r}
transform_routes <- function(df) {
  df %>%
    filter(route_desc == "Sydney Trains Network") %>%
    select(route_id, route_long_name) %>%
    mutate(route_id = as_factor(route_id))
}

transform_stops <- function (df) {
  df %>%
    select(-location_type) %>%
    mutate_at(c("stop_code", "platform_code"), as.factor)
}

transform_trips <- function (df) {
  df %>%
    mutate(direction_id = direction_id %>% as.character %>% as_factor) %>%
    mutate_at(vars(route_id : shape_id), as_factor)
}

transform_stop_times <- function (df) {
  df %>%
    mutate_at(vars(ends_with("_id")), as.factor) %>%
    select(-pickup_type, -drop_off_type, -stop_headsign)
}
```


# Run

Read the data and do repeated joins to create an aggregate data frame.
```{r, message=FALSE}
t_lines <- 
  read_routes() %>% 
  transform_routes

# Match only on route_id
trips <-
  read_trips() %>%
  transform_trips %>%
  inner_join(t_lines)

# Match only on trip_id
stop_times <-
  read_stop_times() %>%
  transform_stop_times %>%
  inner_join(trips) 

# Match only on stop_id
stops <- 
  read_stops() %>% 
  transform_stops %>%
  inner_join(stop_times)

```

